name: "Build Project"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout para main
        uses: actions/checkout@v2
      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Instalar Yarn
        run: npm install -g yarn
      - name: Instalar Dependências
        run: yarn install
      - name: Construir o projeto
        run: yarn build
